global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]  # Make sure this matches the cAdvisor container's address and port
